Projectproperties:
  eureka-tad-dev: ["https://api.cognitedata.com", "EUREKA_TAD_DEV_API_KEY"] # you do not need to specify the default api url
  sebnickelgreenfield: ["https://greenfield.cognitedata.com", "SEBNICKELGREENFIELD_API_KEY"]
ProjectFunctionMap:
  templatefunction:
    - eureka-tad-dev
## if you want to add a second project you can also do the following way:
## make sure you add the APIKEY to Github secrets and add it to the 3 workflow files in .github/workflows
# your_other_project: ["https://api.cognitedata.com", "APIKEY"]

