Projectproperties:
  jp-demo: [ "https://api.cognitedata.com", "JP_DEMO_API_KEY" ]

ProjectFunctionMap:
  synthtsmodel:
    - jp-demo
  lowerthreshold:
    - jp-demo
  absolutedeviance:
    - jp-demo
  tempdeviancecalc:
    - jp-demo
  upperthreshold:
    - jp-demo
  AnomalyDetectionWithMA:
    - jp-demo
  anomaly_detection:
    - jp-demo











## if you want to add a second project you can also do the following way:
## make sure you add the APIKEY to Github secrets and add it to the 3 workflow files in .github/workflows
# your_other_project: ["https://api.cognitedata.com", "APIKEY"]



# Checks for yaml validation