Projectproperties:
  eureka-tad-dev: ["https://api.cognitedata.com", "EUREKA_TAD_DEV_API_KEY"] # you do not need to specify the default api url
  hess: ["https://api.cognitedata.com", "HESS_API_KEY"] # you do not need to specify the default api url
  akerbp: ["https://api.cognitedata.com", "AKERBP_API_KEY"] # you do not need to specify the default api url
  kvaerner-dev: ["https://api.cognitedata.com", "KVAERNER_DEV_API_KEY"] # you do not need to specify the default api url
  sebnickelgreenfield: ["https://greenfield.cognitedata.com", "SEBNICKELGREENFIELD_API_KEY"]
  daw-private: ["https://greenfield.cognitedata.com", "DAW_PRIVATE_API_KEY"]
  air-demo: ["https://greenfield.cognitedata.com", "AIR_DEMO_API_KEY"]
  pgs-dev: ["https://pgs.cognitedata.com", "PGS_DEV_API_KEY"]
  power-demo: ["https://greenfield.cognitedata.com", "POWER_DEMO_API_KEY"]
  dea-dev: ["https://api.cognitedata.com", "DEA_DEV_API_KEY"]
  officerobotics: ["https://greenfield.cognitedata.com", "OFFICEROBOTICS_API_KEY"]
  servi-dev: [ "https://api.cognitedata.com", "SERVI_DEV_API_KEY" ]
  jp-demo: [ "https://api.cognitedata.com", "ZWU3MTFjNGItNTVkZC00ODIxLWE1ZjEtMjY3NzlhNzcxMjY0" ]
  jp-dev: ["https://asia-northeast1-1.cognitedata.com", "JP_DEV_API_KEY"]
  akerbm-dev: ["https://api.cognitedata.com", "AKER_BM_DEV_API_KEY"]
  kvaerner : ["https://api.cognitedata.com", "KVAERNER_API_KEY"]
  test : ["https://statnett.cognitedata.com","TEST_API_KEY"]
  pgs: ["https://pgs.cognitedata.com","PGS_API_KEY"]
  premier-oil-uk: [ "https://api.cognitedata.com","PREMIER_OIL_UK_API_KEY"]
  premier-oil-uk-dev: [ "https://api.cognitedata.com","PREMIER_OIL_UK_DEV_API_KEY"]
  ak-cepj: ["https://api.cognitedata.com","AK_CEPJ_API_KEY"]
  wd-prod: ["https://api.cognitedata.com","WD_PROD_API_KEY"]
  utility-demo: ["https://api.cognitedata.com","UTILITY_DEMO_API_KEY"]
  fusion: ["https://api.cognitedata.com","FUSION_API_KEY"]
  air-azure-testing:
    base_url: "https://azure-dev.cognitedata.com"
    tenant_id: "4f1bdc32-4c0b-4e0a-9a22-13b1e5c14319"
    client_id: "471be628-6a0f-4159-910f-e79f770ff7db"
    secret_name: "AIR_AZURE_TESTING_SECRET"
    token_url: "https://login.microsoftonline.com/4f1bdc32-4c0b-4e0a-9a22-13b1e5c14319/oauth2/v2.0/token"
    scopes: ["https://azure-dev.cognitedata.com/.default"]
  air-staging-oidc:
    base_url: "https://greenfield.cognitedata.com"
    tenant_id: "4f1bdc32-4c0b-4e0a-9a22-13b1e5c14319"
    client_id: "471be628-6a0f-4159-910f-e79f770ff7db"
    secret_name: "AIR_AZURE_TESTING_SECRET"
    token_url: "https://login.microsoftonline.com/4f1bdc32-4c0b-4e0a-9a22-13b1e5c14319/oauth2/v2.0/token"
    scopes: ["https://greenfield.cognitedata.com/.default"]
  accenture-dev-1:
    base_url: "https://api.cognitedata.com"
    tenant_id: "b50d8ea7-50f7-44c1-b1e1-96d32db3b4ea"
    client_id: "fb387949-17b0-44f2-94ba-bdeccb7772ea"
    secret_name: "ACCENTURE_DEV_ONE_SECRET"
    token_url: "https://login.microsoftonline.com/b50d8ea7-50f7-44c1-b1e1-96d32db3b4ea/oauth2/v2.0/token"
    scopes: [ "https://api.cognitedata.com/.default" ]
  arba-dev:
    base_url: "https://api.cognitedata.com"
    tenant_id: "7f57d068-1c3c-4091-8c50-a22bd86c1220"
    client_id: "2aa2864a-a681-48e0-92a7-32bace6eb222"
    secret_name: "ARBA_DEV_ONE_SECRET"
    token_url: "https://login.microsoftonline.com/7f57d068-1c3c-4091-8c50-a22bd86c1220/oauth2/v2.0/token"
    scopes: [ "https://api.cognitedata.com/.default" ]
  nakajima-demo:
    base_url: "https://greenfield.cognitedata.com"
    tenant_id: "c2bafc3c-94d1-4831-b4f7-8b568780910a"
    client_id: "d1b36d6b-335b-4ecf-849f-a0e218f5bf22"
    secret_name: "NAKAJIMA_DEMO_SECRET"
    token_url: "https://login.microsoftonline.com/c2bafc3c-94d1-4831-b4f7-8b568780910a/oauth2/v2.0/token"
    scopes: ["https://greenfield.cognitedata.com/.default"]

ProjectFunctionMap:
  abbdataquality:
    - akerbp 
  synthtsmodel:
    - air-demo
    - air-staging-oidc
    - arba-dev
    # - daw-private
    - eureka-tad-dev
    - hess
    - kvaerner-dev
    - pgs-dev
    # - power-demo
    # - officerobotics
    - dea-dev
    - servi-dev
    - jp-demo
    - jp-dev
    - akerbm-dev
    - kvaerner
    - test
    - pgs
    - premier-oil-uk
    - premier-oil-uk-dev
    - ak-cepj
    - wd-prod
    - utility-demo
    - accenture-dev-1
    - nakajima-demo
    - fusion
  lowerthreshold:
    - air-demo
    - air-staging-oidc
    - akerbp
    - arba-dev
    # - daw-private
    - eureka-tad-dev
    - hess
    # - officerobotics
    - pgs-dev
    # - power-demo
    - dea-dev
    - servi-dev
    - jp-demo
    - jp-dev
    - akerbm-dev
    - kvaerner
    - test
    - pgs
    - premier-oil-uk
    - premier-oil-uk-dev
    - ak-cepj
    - wd-prod
    - utility-demo
    - accenture-dev-1
    - nakajima-demo
    - fusion
  absolutedeviance:
    - air-demo
    - air-staging-oidc
    - akerbp
    - arba-dev
    # - daw-private
    - eureka-tad-dev
    # - officerobotics
    - hess
    - kvaerner-dev
    - pgs-dev
    # - power-demo
    - dea-dev
    - servi-dev
    - jp-demo
    - jp-dev
    - akerbm-dev
    - kvaerner
    - test
    - pgs
    - premier-oil-uk
    - premier-oil-uk-dev
    - ak-cepj
    - wd-prod
    - utility-demo
    - accenture-dev-1
    - nakajima-demo
    - fusion
  tempdeviancecalc:
    - air-demo
    - air-staging-oidc
    - akerbp
    - arba-dev
    # - daw-private
    - eureka-tad-dev
    # - officerobotics
    - hess
    - kvaerner-dev
    - pgs-dev
    # - power-demo
    - dea-dev
    - servi-dev
    - jp-demo
    - jp-dev
    - akerbm-dev
    - kvaerner
    - test
    - pgs
    - premier-oil-uk
    - premier-oil-uk-dev
    - ak-cepj
    - wd-prod
    - utility-demo
    - accenture-dev-1
    - nakajima-demo
    - fusion
  upperthreshold:
    - air-demo
    - air-staging-oidc
    - akerbp
    - arba-dev
    # - daw-private
    - eureka-tad-dev
    - hess
    - kvaerner-dev
    # - officerobotics
    - pgs-dev
    # - power-demo
    - dea-dev
    - servi-dev
    - jp-demo
    - jp-dev
    - akerbm-dev
    - kvaerner
    - test
    - pgs
    - premier-oil-uk
    - premier-oil-uk-dev
    - ak-cepj
    - wd-prod
    - utility-demo
    - accenture-dev-1
    - nakajima-demo
    - fusion
  AnomalyDetectionWithMA:
    - air-demo
    - air-staging-oidc
    - arba-dev
    # - daw-private
    - eureka-tad-dev
    # - officerobotics
    - hess
    - kvaerner-dev
    - pgs-dev
    # - power-demo
    - dea-dev
    - servi-dev
    - jp-demo
    - jp-dev
    - akerbm-dev
    - kvaerner
    - test
    - pgs
    - premier-oil-uk
    - premier-oil-uk-dev
    - ak-cepj
    - wd-prod
    - utility-demo
    - accenture-dev-1
    - nakajima-demo
    - fusion
  gasdetectiondrift:
    - akerbp
  testmodelfunction:
    - eureka-tad-dev
  doublethreshold:
    - air-demo
    - air-staging-oidc
    - arba-dev
  ts2threshold1:
    - air-demo
    - eureka-tad-dev
  four_thresholds_model:
    - air-demo
    - air-staging-oidc
    - ak-cepj
    - arba-dev
    - eureka-tad-dev
  anomaly_detection:
    - jp-demo











## if you want to add a second project you can also do the following way:
## make sure you add the APIKEY to Github secrets and add it to the 3 workflow files in .github/workflows
# your_other_project: ["https://api.cognitedata.com", "APIKEY"]



# Checks for yaml validation