Projectproperties:
  my-project: ['https://api.cognitedata.com', '!-gh,Q0&@*2PxTV@gA!={e#,;fKO:U']
ProjectFunctionMap:
  my_function:
    - air-function
## if you want to add a second project you can also do the following way:
## make sure you add the APIKEY to Github secrets and add it to the 3 workflow files in .github/workflows
# your_other_project: ["https://api.cognitedata.com", "APIKEY"]

