schedule:
  cronExpression: 0 0 1 * *

modelDescription:
  frontEndName: "PCA model"
  description: "When PC1 has outliner, an alert is created."

modelSettings:
  modelVersion: "1.0.0" # set the version of your model here
  sendAlerts: True  # set to True if you want the events of this model being propagated to the front end
  displayInFrontEnd: True # set to True if it should be selectable in the front end
  backfill: True

fields:
  sensor_11:
    name: "sensor_11"
    description: "A time series that is going to be monitored"
    type: "TimeSeries"
  pc1:
    name: "pc1"
    description: "When the selected time series crosses above on this threshold an alert will be created."
    type: "TimeSeries"
  anomaly_pc1:
    name: "anomaly_pc1"
    description: "When pc1 indicate anomaly, set anomaly flag."
    type: "TimeSeries"
  machine_status:
    name: "machine_status"
    description: "Actual machine status."
    type: "TimeSeries"

visualization:
  timeSeries:
    fields: ["sensor_11", "anomaly_pc1", "machine_status"]
  grouping: [["sensor_11", "anomaly_pc1", "machine_status"]]